flask:
  DEBUG: 1
  host: 127.0.0.1
  port: 5000
connection:
  usb: /dev/ttyUSB0
  baudrate: 9600
  parity: serial.PARITY_NONE
  bytesize: 8
  stopbits: 1
  timeout: 3
thermometers:
  - id: 1
    name: Ground Floor
    status:
    temperature:
  - id: 2
    name: First Floor
    status:
    temperature:
  - id: 3
    name: Outside
    status:
    temperature:
  - id: 4
    name: Boiler
    status:
    temperature:
